---
# BEST PRACTICE: Переменные специфичные для мастер-сервера
# Разделение конфигурации по ролям упрощает управление

# === Настройки репликации ===
# Пароль для пользователя репликации (должен быть в vault)
replica_password: "{{ vault_replica_password }}"

# IP адреса для репликации (берутся из inventory)
postgres_master_ip: "{{ hostvars['postgres_master']['ansible_host'] }}"
postgres_slave_ip: "{{ hostvars['postgres_slave']['ansible_host'] }}"

# === PostgreSQL конфигурация для Master ===
# BEST PRACTICE: Централизованное управление конфигурацией через переменные
postgresql_master_config:
  # Слушать на IP мастера, а не localhost
  - regexp: "#listen_addresses = 'localhost'"
    line: "listen_addresses = '{{ postgres_master_ip }}'"
  
  # WAL level для hot standby репликации
  - regexp: "#wal_level = minimal"
    line: "wal_level = hot_standby"
  
  # Синхронный коммит на уровне локального сервера
  - regexp: "#synchronous_commit = on"
    line: "synchronous_commit = local"
  
  # Включаем режим архивирования WAL
  - regexp: "#archive_mode = off"
    line: "archive_mode = on"
  
  # Команда для архивирования (для Debian путь другой чем в RedHat)
  - regexp: "#archive_command = ''"
    line: "archive_command = 'cp %p {{ postgresql_data_dir }}/../archive/%f'"
  
  # Максимум слейвов (2 достаточно для тестирования)
  - regexp: "#max_wal_senders = 0"
    line: "max_wal_senders = 2"
  
  # Хранить 2 сегмента WAL для слейвов
  - regexp: "#wal_keep_segments = 0"
    line: "wal_keep_segments = 2"
  
  # Имя синхронного слейва
  - regexp: "#synchronous_standby_names = ''"
    line: "synchronous_standby_names = 'slave01'"

# Путь к директории архивов WAL
postgresql_archive_dir: "{{ postgresql_data_dir }}/../archive"

# === pg_hba.conf настройки ===
# BEST PRACTICE: Шаблонизация конфигурации вместо хардкода
postgresql_hba_entries:
  - "host replication repluser 127.0.0.1/32 md5"
  - "host replication repluser {{ postgres_master_ip }}/32 md5"
  - "host replication repluser {{ postgres_slave_ip }}/32 md5"
  - "host all postgres {{ postgres_connection_ip }}/32 md5"

# Пользователь репликации
replication_user:
  name: "repluser"
  role_attr_flags: "REPLICATION,LOGIN"
  password: "{{ replica_password }}"
